
 
CREATE TABLE FINANCIAMENTO(
  idFinanciamento Number(10)  NOT NULL,
  idCliente Number(10) NOT NULL,
  Tipo Number(1) NOT NULL,
  ValorTotal Number(18, 2) NOT NULL,
 CONSTRAINT PK_FINANCIAMENTO PRIMARY KEY 
(
  idFinanciamento 
) 
);


-- Generate ID using sequence and trigger
CREATE SEQUENCE FINANCIAMENTO_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FINANCIAMENTO_seq_tr
 BEFORE INSERT ON FINANCIAMENTO FOR EACH ROW
 WHEN (NEW.idFinanciamento IS NULL)
BEGIN
 SELECT FINANCIAMENTO_seq.NEXTVAL INTO :NEW.idFinanciamento FROM DUAL;
END;
